on: [push, pull_request]
name: CI

jobs:
  unit:
    strategy:
      fail-fast: false
      matrix:
        os: [ "ubuntu" ]
        go: [ "1.17.x", "1.18.x" ]
    env:
      COVERAGES: ""
    runs-on: ${{ matrix.os }}-latest
    name: ${{ matrix.os}} (go ${{ matrix.go }})
    defaults:
      run:
        working-directory: go-car-mirror
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: go-car-mirror
      - name: Checkout kubo repo
        uses: actions/checkout@v3
        with:
          repository: ipfs/kubo
          path: kubo
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Go information
        run: |
          go version
          go env
      - name: Build
        run: make build build-plugin
      - name: Run tests
        run: make test
      - name: Check formatted
        run: gofmt -l .
      - name: Run sharness tests
        run: make sharness-v